export const GAME_CONFIG = {
  gravity: [0, -1.8, 0] as [number, number, number],
  // The ball enters from above the camera's visible play area.
  imageStart: [0, 2, 0] as [number, number, number],
  imageSize: 1,
  floorY: -2.1,
  // Keep the ceiling well above the camera/XR viewport so there is room to play.
  ceilingY: 5.5,
  wallX: 1.9,
  wallHeight: 7.6,
  wallCenterY: 1.7,
  boundaryThickness: 0.05,
  bounce: 0.55,
  friction: 0.08,
  linearDamping: 0.4,
  angularDamping: 0.12,
  boundaryColor: "#7dd3fc",
  boundaryOpacity: 0.08,
  tossImpulse: 10,
  hitHorizontalImpulse: 0.38,
  hitTorqueImpulse: 0.8,
  maxHorizontalVelocity: 2.4,
  maxAngularVelocity: 2,
  maxUpwardVelocity: 1.6,
  resetY: -2.5,
  sessionDuration: 30,
  gravityPerLevel: 0.18,
  maxLevel: 8,
  targetRadius: 0.32,
  basePoints: 1,
  targetBonus: 2,
  impactDurationMs: 260,
  impactColor: "#fef08a",
  impactOpacity: 0.8,
  comboScoreMultiplier: 1,
  faceTrackingFps: 24,
  faceBoxColor: "#b9e6ff",
  faceBoxOpacity: 0.05,
  faceBoxBorderWidth: 2,
  faceBoxPadding: 0.015,
  faceHitCooldownMs: 260,
  faceHitImpulseScale: 1,
  faceHitTorqueScale: 1,
} as const;

export const DEFAULT_IMAGE_URL = "/ball.png";
